package com.example.myapplication;

import android.app.NotificationChannel;
import android.app.NotificationManager;
import android.app.PendingIntent;
import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;
import android.os.Build;
import android.util.Log;

import androidx.core.app.NotificationCompat;
import androidx.core.app.NotificationManagerCompat;

public class AlertReceiver extends BroadcastReceiver {

    private static final String TAG = "AlertReceiver";
    private static final String CHANNEL_ID = "alert_channel";

    @Override
    public void onReceive(Context context, Intent intent) {
        String msg = intent.getStringExtra("alert_message");

        if (msg == null || msg.isEmpty()) {
            msg = "Monitoring alert detected";
        }

        Log.d(TAG, "Received alert broadcast: " + msg);

        // Android 8+ requires a notification channel.
        createNotificationChannel(context);

        // Open MainActivity when the notification is tapped.
        Intent openIntent = new Intent(context, MainActivity.class);
        openIntent.setFlags(
                Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_CLEAR_TOP
        );

        PendingIntent pendingIntent = PendingIntent.getActivity(
                context,
                0,
                openIntent,
                PendingIntent.FLAG_UPDATE_CURRENT | PendingIntent.FLAG_IMMUTABLE
        );

        // Build the notification content.
        NotificationCompat.Builder builder =
                new NotificationCompat.Builder(context, CHANNEL_ID)
                        .setSmallIcon(R.mipmap.ic_launcher)
                        .setContentTitle("Home Monitoring Alert")
                        .setContentText(msg)
                        .setStyle(new NotificationCompat.BigTextStyle().bigText(msg))
                        .setPriority(NotificationCompat.PRIORITY_HIGH)
                        .setAutoCancel(true)
                        .setContentIntent(pendingIntent);

        // Use a time-based ID so multiple alerts can appear separately.
        NotificationManagerCompat manager =
                NotificationManagerCompat.from(context);

        int id = (int) (System.currentTimeMillis() & 0xFFFFFFF);
        manager.notify(id, builder.build());
    }

    private void createNotificationChannel(Context context) {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            String name = "Monitoring Alerts";
            String description = "High-priority alerts generated by the monitoring system";
            int importance = NotificationManager.IMPORTANCE_HIGH;

            NotificationChannel channel =
                    new NotificationChannel(CHANNEL_ID, name, importance);

            channel.setDescription(description);

            NotificationManager manager =
                    context.getSystemService(NotificationManager.class);

            if (manager != null) {
                manager.createNotificationChannel(channel);
            }
        }
    }
}
